### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by okethan** [DeveloperQynx/ViVScript#4]
What do i put in the hotkey scripts area? or something else?

**Comment by DeveloperQynx** [comment]
> [Starts/Stops Keybind](https://github.com/DeveloperQynx/ViVScript#f3---startsstops)
If this wasn't your question, please lemme know! I'm sorry for a very vague response, I've been pretty busy with other projects and this script has been a pretty low priority. A new & better version is in the works in case you're curious!

**Comment by okethan** [comment]
No, it about how to excecute it like with autohotkey, like do I paste it
into the scripts or how?

**Comment by DeveloperQynx** [comment]
## Installation & Setup
### Downloading
- First, you're going to want to [download](https://www.autohotkey.com/download/ahk-install.exe) **AutoHotkey**, as this is an **AutoHotkey** script.
  - Just follow through the setup prompt that **AutoHotkey** gives you.
- Next, [download](https://github.com/DeveloperQynx/ViVScript/releases/download/v3.4.1/ViVScript.ahk) my script, **ViVScript**.
### Setting up & Executing
- After downloading those and setting up **AutoHotkey**, run **ViVScript**.
  - A task should appear in your [System Tray](https://www.webopedia.com/TERM/S/system_tray.html). 
  - If so, that means it's running and you're free to use **ViVScript**!

Again, if this doesn't work, lemme know.
  - Like I said, [v4](https://github.com/DeveloperQynx/ViVScript/projects/3) is in the works and will be a lot more intuitive.

> My apologies for making everything super confusing. I hope this helped!

**Comment by DeveloperQynx** [comment]
### Question Resolved
Thanks! <3
